#ifndef ZZ_BINARY_OPERATORS_H
#define ZZ_BINARY_OPERATORS_H

#include <rpr.h>

enum zz_binary_operator {
	ZZ_BINARY_OPERATOR_ADD,
	ZZ_BINARY_OPERATOR_SUBTRACT,
	ZZ_BINARY_OPERATOR_MULTIPLY,
	ZZ_BINARY_OPERATOR_DIVIDE,
	ZZ_BINARY_OPERATOR_MODULO
};

#endif /* ZZ_BINARY_OPERATORS_H */
